##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    #----生产
    url: jdbc:mysql://rm-2zewe8hvt8mc677z1wo.mysql.rds.aliyuncs.com:3306/half_classroom?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=round&allowMultiQueries=true&useSSL=false
    #----开发
    #url: jdbc:mysql://rm-2ze23n699786i4998oo.mysql.rds.aliyuncs.com:3306/half_classroom?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=round&allowMultiQueries=true&useSSL=false
    #url: jdbc:mysql://localhost:3306/half_classroom?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=round&allowMultiQueries=true&useSSL=false
    password: Bbqwe123!@#
    username: root
    #password: 1234
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: config,stat,wall,log4j
    #最大连接数
    maxActive: 1500
    #初始连接数
    initialSize: 5
    #最小空闲
    minIdle: 5
    #打开sql监控
    openmergeSql: true

  rabbitmq:
    host: 47.94.193.125
    username: dev
    password: 123456
    listener:
      acknowledge-mode: manual
logging:
  level.root: info
  level.com.halfroom: debug
  path: logs/
  file: dist.log
