
spring:
  profiles: pro
  datasource:
      url: jdbc:mysql://rm-2zewe8hvt8mc677z1wo.mysql.rds.aliyuncs.com:3306/half_classroom?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=round&allowMultiQueries=true&useSSL=false
      username: root
      password: Bbqwe123!@#
      filters: stat,wall,log4j
    #最大连接数
      maxActive: 1500
    #初始连接数
      initialSize: 5
    #最小空闲
      minIdle: 5
    #打开sql监控
      openmergeSql: true
  rabbitmq:
    host: 39.106.147.176      
    username: dev
    password: 123456
    listener:
      acknowledge-mode: manual
logging:
  level.root: info
  level.com.halfroom: DEBUG
  path: logs/
  file: dist.log