##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
   
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: config,stat,wall,log4j
    #最大连接数
    maxActive: 1500
    #初始连接数
    initialSize: 5
    #最小空闲
    minIdle: 5
    #打开sql监控
    openmergeSql: true

  rabbitmq:
    host: 47.94.193.125
    username: dev
    password: 123456
    listener:
      acknowledge-mode: manual
logging:
  level.root: info
  level.com.halfroom: debug
  path: logs/
  file: dist.log
